services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  backend:
    build: ./todo-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  frontend:
    build: ./todo-frontend
    ports:
      - "3001:3000"
volumes:
  mongodb_data:
